### PR TITLE
Fix frequency correction for client uplink

### LINKED ISSUE #43: Frequency offset estimation does not work when using different UL and DL bands
Currently, the client estimates the frequency offset in the DL band. The offset estimation value is calculated in Hz and added to the DL carrier frequency in Hz. For the Uplink, the same offset value is added to the Uplink carrier frequency. 

```c
cfo_hz = The calculated carrier frequency offset in Hz by using received samples in the DL
// Correct UL and DL LO frequencies by the offset
DL_LO_corrected = DL_LO + cfo_hz
UL_LO_corrected = UL_LO + cfo_hz
```

This is only valid if the UL and DL carrier frequencies are similar. If the UL and DL are significantly different, e.g. 430 MHz and 1300 MHz, the offset for the 1300 MHz band is 1300/430 times the offset in the 430 MHz band. We have to consider this factor when correcting the UL frequency offset at the client side.

This has to be changed in the inital carrier sync function:
https://github.com/HAMNET-Access-Protocol/HNAP4PlutoSDR/blob/8c70b6856facca2182fe565f00e3595148be66c4/src/runtime/client.c#L339

I have to check whether this affects other parts of the code.

### PR DESCRIPTION
**Pull request by lukasostendorf**
We calculate the absolute frequency offset for the DL band. To use this in the UL band we have to scale the offset according to the used UL/DL bands.

We do not compute offset ppm values, since `ofdmframesync_get_cfo()` returns a value in radians, which can be converted to absolute values more easily.

### CODE REVIEW

File: src/runtime/client.c [hunk 1]
```diff
@@ -351,11 +351,13 @@ void phy_carrier_sync(PhyUE phy, platform hw) {
...
-  pluto_set_tx_freq(hw, ul_lo + (long)cfo_hz);
-  pluto_set_rx_freq(hw, dl_lo + (long)cfo_hz);
+  pluto_set_tx_freq(hw,
+                    ul_lo + (long long)(cfo_hz * (float)ul_lo / (float)dl_lo));
+  pluto_set_rx_freq(hw, dl_lo + (long long)cfo_hz);
   LOG(INFO, "[CLIENT] retune transceiver with cfo %.3fHz:\n", cfo_hz);
-  LOG(INFO, "[CLIENT] TX LO freq: %lldHz\n", ul_lo + (long)cfo_hz);
-  LOG(INFO, "[CLIENT] RX LO freq: %lldHz\n", dl_lo + (long)cfo_hz);
+  LOG(INFO, "[CLIENT] TX LO freq: %lldHz\n",
+      ul_lo + (long long)(cfo_hz * (float)ul_lo / (float)dl_lo));
```
Comment (dl1com) [inline src/runtime/client.c]: Please introduce new variables for the corrected rx and tx lo frequencies for better readability and re-usage for assignment (lines 355, 356) and log output (lines 359, 360)

**Review by dl1com — CHANGES_REQUESTED** [review]

**Review by dl1com — APPROVED** [review]
